org: ruucmworking
# NOTE: update this with your service name
app: my-lambda-app
service: test-01

provider:
  name: aws
  runtime: nodejs10.x
  # stage: dev
  region: us-west-2
  # Region List - https://docs.aws.amazon.com/general/latest/gr/rande.html
  # Supported Serverless Dashboard Regions - https://serverless.com/framework/docs/dashboard#supported-runtimes-and-regions
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
